#!/bin/bash

# =================================================================
# macOS AI 協作環境優化腳本
# 功能：升級 Bash 並安裝 GNU 系列工具，消除 AI 指令兼容性問題
# =================================================================

echo "🚀 開始配置優化環境..."

# 1. 檢查 Homebrew 是否安裝
if ! command -v brew &> /dev/null; then
    echo "❌ 找不到 Homebrew，請先安裝 Homebrew: https://brew.sh/"
    exit 1
fi

# 2. 安裝最新版 Bash 與 GNU 系列工具
echo "📦 正在透過 Homebrew 安裝工具 (這可能需要一點時間)..."
brew install bash coreutils findutils gnu-sed gnu-tar grep awk

# 3. 獲取 Homebrew Bash 的路徑
BREW_BASH_PATH=$(brew --prefix)/bin/bash

# 4. 將環境設定寫入 .zshrc (你的外殼)
# 我們會設定別名，讓 sed 直接指向 gsed，這樣 AI 產出的指令就能直接跑
echo "📝 正在設定環境變數與 Alias..."

{
    echo ""
    echo "# --- AI 協作優化設定 (Generated by AI Script) ---"
    echo "# 讓系統優先使用 Homebrew 安裝的 GNU 工具"
    echo "export PATH=\"$(brew --prefix coreutils)/libexec/gnubin:\$PATH\""
    echo "export PATH=\"$(brew --prefix findutils)/bin:\$PATH\""
    echo ""
    echo "# 設定常用 GNU 工具別名，確保 AI 指令相容性"
    echo "alias sed='gsed'"
    echo "alias tar='gtar'"
    echo "alias grep='ggrep'"
    echo "alias awk='gawk'"
    echo ""
    echo "# 強制指定開發環境的 Bash 版本"
    echo "export AI_BASH_PATH=\"$BREW_BASH_PATH\""
    echo "# -----------------------------------------------"
} >> ~/.zshrc

echo "✅ 設定完成！"
echo "👉 請執行 'source ~/.zshrc' 來啟用設定。"
echo "💡 現在你的系統已經具備最新的 Bash $( $BREW_BASH_PATH --version | head -n 1 )"
echo "💡 且 sed/grep/find 等指令已切換為 AI 最愛的 GNU 版本。"